name: challenge_shop
description: 挑战app积分商城

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
#  sticky_headers: "^0.1.7"#listview悬停section
  flutter_swiper : ^1.1.4 #轮播图
  marquee: ^0.1.0 #跑马灯效果
  rxdart: ^0.19.0
  json_annotation: ^2.0.0
  event_bus: ^1.0.1
  oktoast: ^2.0.0
  pull_to_refresh: ^1.1.6
  flutter_spinkit: ^3.0.0
  flutter_picker: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.1.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/3.0x/ic_success.png
    - assets/imgs/3.0x/bg_shop_header.png
    - assets/imgs/3.0x/ic_question.png
    - assets/imgs/3.0x/ic_news.png
    - assets/imgs/3.0x/ic_cover.png

  #mock数据
    - assets/json/exchange_history.json
    - assets/json/my_score_info.json
    - assets/json/order_detail.json
    - assets/json/product_detail.json
    - assets/json/product_detail1.json
    - assets/json/products.json
    - assets/json/score_history.json
    - assets/json/district.json


